name: HA LLM Ops
version: 0.0.36
slug: ha_llm_ops
description: LLM-powered add-on that analyzes Home Assistant incidents and suggests safe fixes.
arch:
  - aarch64
  - amd64
startup: application
boot: auto
homeassistant_api: true
ingress: true
ingress_port: 8000
panel_icon: mdi:robot
panel_title: HA LLM Ops
options:
  log_level: info
  buffer_size: 100
  problem_dir: /data/problems
  llm_backend: mock
  openai_api_key: ""
  ha_ws_url: ws://supervisor/core/websocket
schema:
  log_level: list(debug|info|warning|error)?
  buffer_size: int
  problem_dir: str
  llm_backend: list(mock|openai)?
  openai_api_key: password?
  ha_ws_url: str?
icon: addons/ha-llm-ops/icon.png
logo: addons/ha-llm-ops/icon.png
