name: HA LLM Ops
version: 0.0.0
slug: ha_llm_ops
description: Placeholder HA LLM Ops add-on.
arch:
  - aarch64
  - amd64
startup: application
boot: auto
options:
  log_level: info
  buffer_size: 100
  incident_dir: /data/incidents
schema:
  log_level: list(debug|info|warning|error)?
  buffer_size: int
  incident_dir: str
