name: HA LLM Ops
version: 0.0.42
slug: ha_llm_ops
description: LLM-powered add-on that analyzes Home Assistant problems and suggests safe fixes.
arch:
  - aarch64
  - amd64
startup: application
boot: auto
homeassistant_api: true
ingress: true
ingress_port: 8000
panel_icon: mdi:robot
panel_title: Autofix Problems
options:
  log_level: info
  buffer_size: 10
  analysis_rate_seconds: 60
  analysis_max_lines: 20
  openai_api_key: ""
schema:
  log_level: list(debug|info|warning|error)?
  buffer_size: int
  analysis_rate_seconds: int?
  analysis_max_lines: int?
  openai_api_key: password?
icon: addons/ha-llm-ops/icon.png
logo: addons/ha-llm-ops/icon.png
